#!/bin/bash
#
# Structural checks on a built ISO. These are the invariants that distinguish an
# ISO which merely built from one that can actually boot -- every failure mode
# here has been observed producing a clean, successful build:
#
#   * an initramfs with no archiso hook, which panics with no root filesystem
#   * boot configs naming a kernel or initramfs the ISO does not contain
#   * the wrong architecture's EFI bootloader
#
# Runs against release/*.iso when one exists and skips otherwise, so test/all
# stays fast and VM-free. Pass a specific image as $1 to check that one.

set -euo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)

pass() {
  printf 'ok - %s\n' "$1"
}

fail() {
  local description="$1"
  local detail="${2:-}"

  [[ -n $detail ]] && printf '%s\n' "$detail" >&2
  printf 'not ok - %s\n' "$description" >&2
  exit 1
}

skip() {
  printf 'ok - %s # SKIP %s\n' "$1" "${2:-}"
}

iso="${1:-}"
if [[ -z $iso ]]; then
  iso=$(\ls -t "$ROOT"/release/*.iso 2>/dev/null | head -n1 || true)
fi

if [[ -z $iso || ! -f $iso ]]; then
  skip "iso structure" "no ISO in release/; build one first"
  exit 0
fi

for tool in bsdtar; do
  command -v "$tool" >/dev/null || fail "$tool is required"
done

# The ISO filename carries the architecture archiso built it for.
case "${iso##*/}" in
*aarch64*) arch=aarch64 efi=BOOTAA64.EFI ;;
*x86_64*) arch=x86_64 efi=BOOTX64.EFI ;;
*) fail "cannot determine architecture from ${iso##*/}" ;;
esac

listing=$(bsdtar -tf "$iso" 2>/dev/null) || fail "cannot read $iso as an archive"

has() {
  printf '%s\n' "$listing" | grep -qxF "$1"
}

# --- the ISO is bootable at all -------------------------------------------

file "$iso" | grep -q 'ISO 9660' ||
  fail "$arch: not an ISO 9660 image"
pass "$arch: ISO 9660 image"

has "EFI/BOOT/$efi" ||
  fail "$arch: missing EFI/BOOT/$efi" "$(printf '%s\n' "$listing" | grep -i '\.efi$' || true)"
pass "$arch: EFI/BOOT/$efi present"

# The other architecture's loader must NOT be there: its presence means the
# profile arch and the build arch disagreed somewhere.
case $arch in
aarch64) other=EFI/BOOT/BOOTX64.EFI ;;
*) other=EFI/BOOT/BOOTAA64.EFI ;;
esac
if has "$other"; then
  fail "$arch: unexpected $other in an $arch image"
fi
pass "$arch: no foreign EFI loader"

has "arch/$arch/airootfs.sfs" ||
  fail "$arch: missing arch/$arch/airootfs.sfs"
pass "$arch: squashfs root present"

# --- boot configs point at files that exist -------------------------------
#
# grub.cfg is generated by substituting %ARCH% and, on aarch64, rewriting the
# kernel filenames. A mismatch here is invisible until the bootloader runs.

grub_cfg=$(bsdtar -xOf "$iso" boot/grub/grub.cfg 2>/dev/null) ||
  fail "$arch: no boot/grub/grub.cfg in image"

referenced=$(printf '%s\n' "$grub_cfg" |
  grep -oE '/arch/boot/[^ ]*(vmlinuz|initramfs)[^ ]*' | sort -u)

[[ -n $referenced ]] ||
  fail "$arch: grub.cfg references no kernel or initramfs"

while read -r path; do
  [[ -n $path ]] || continue
  has "${path#/}" ||
    fail "$arch: grub.cfg references $path, absent from the image" \
      "$(printf '%s\n' "$listing" | grep "^arch/boot/" || true)"
done <<<"$referenced"
pass "$arch: every kernel/initramfs grub.cfg names exists in the image"

# --- the live initramfs can actually mount the medium ---------------------
#
# The archiso hook is what finds and mounts airootfs.sfs off the boot medium.
# Without it the kernel boots and panics. This has happened: linux-aarch64 owns
# its own mkinitcpio preset, which builds against /etc/mkinitcpio.conf -- and
# omarchy-settings replaces that file with the *target* system's hooks.

initramfs_path=$(printf '%s\n' "$referenced" | grep 'initramfs' | head -n1)
initramfs_path="${initramfs_path#/}"

if ! command -v lsinitcpio >/dev/null; then
  skip "$arch: initramfs carries the archiso hook" "lsinitcpio not installed"
  exit 0
fi

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

bsdtar -xOf "$iso" "$initramfs_path" >"$work/initramfs.img" 2>/dev/null ||
  fail "$arch: cannot extract $initramfs_path"

hooks=$(lsinitcpio "$work/initramfs.img" 2>/dev/null | grep -oE 'hooks/[a-z_0-9-]+$' | sed 's|hooks/||' | sort -u)

printf '%s\n' "$hooks" | grep -qx archiso ||
  fail "$arch: initramfs has no archiso hook; this ISO would panic on boot" \
    "hooks present: $(printf '%s' "$hooks" | tr '\n' ' ')"
pass "$arch: initramfs carries the archiso hook"

printf '%s\n' "$hooks" | grep -qx archiso_loop_mnt ||
  fail "$arch: initramfs missing archiso_loop_mnt" \
    "hooks present: $(printf '%s' "$hooks" | tr '\n' ' ')"
pass "$arch: initramfs carries archiso_loop_mnt"
